### ISSUE TITLE
[FR] 当已存在折叠的选项页浮窗时, 再次点击ob设置的齿轮图标, 会把折叠的选项页浮窗再展开

### ISSUE THREAD

**Issue by XMB-7** [wish5115/obsidian-floating-settings#1]
当打开一个配置页浮窗并将之折叠后, 或者基于操作习惯, 或者因为暗色主题折叠之后不容易注意到有浮窗存在, 而导致还是去点击ob自带的打开配置页面的按钮, 此时是完全无响应的, 然后才反应过来得去展开折叠的浮窗.

因此希望能够在有浮窗折叠时, 再次点击ob设置的齿轮图标, 会自动把折叠的选项页浮窗展开. 会让易用度再上一台阶.

**Comment by wish5115** [comment]
感谢反馈！

已增加了这个功能，新版本下载：https://github.com/wish5115/obsidian-floating-settings/releases/tag/0.0.11
