### ISSUE TITLE
[FR] 当聚焦切换回浮窗配置页面时, 自动刷新配置浮窗页面.

### ISSUE THREAD

**Issue by XMB-7** [wish5115/obsidian-floating-settings#2]
比如: 先打开配置页浮窗, 进入本地插件页面, 然后将之折叠. 然后执行命令把插件a关闭. 此时再展开配置页浮窗, 发现插件a仍显示为开启状态, 此时需要先切换到其他页面, 比如快捷键页面, 再切换回插件页面, 才能看到a已显示为关闭.

因此希望如果可以的话, 能在切换聚焦时(比如展开浮窗后鼠标点击一下浮窗内部区域)就自动刷新配置页面. 如果能在点击浮窗标题栏将之展开的同时就视为时在切换聚焦从而进行自动刷新, 那就更好不过了. 以及当点击ob齿轮按钮展开已折叠的浮窗页面时(#1)也能自动刷新.

**Comment by wish5115** [comment]
感谢反馈！

已经修复这个问题，新版本下载地址：https://github.com/wish5115/obsidian-floating-settings/releases/tag/0.0.12

效果如图：

![comm](https://github.com/wish5115/obsidian-floating-settings/assets/5248206/89c8bfc4-730b-4ba3-8131-a9f325a04845)
