### ISSUE TITLE
[FR] 折叠的配置页浮窗在展开时, 如果部分超出屏幕范围, 不自动弹回到屏幕之内.

### ISSUE THREAD

**Issue by XMB-7** [wish5115/obsidian-floating-settings#3]
目前的效果是:
<img src=https://github.com/wish5115/obsidian-floating-settings/assets/65625632/b34158e1-9cc0-4f79-a838-04539c65fd16 width=300>

预期的效果是:
<img src=https://github.com/wish5115/obsidian-floating-settings/assets/65625632/e7ca47a0-15f8-4ccb-9727-cff945530ea1 width=300>

---

使用该插件往往是为了无视野遮蔽地调试某一选项, 从而将之浮窗化乃至折叠最小化. 
在此应用场景下, 如果用户还是选择将已折叠的浮窗部分移出屏幕, 那往往还是为了避免视野遮蔽, 所以此时展开回完整浮窗时, 我个人认为最好是不要自动调整浮窗位置将之完整移回屏幕, 而就在原题头位置来进行展开, 否则刚调好的无遮蔽又得重新来一遍.

当然对此可以增加一个配置选项, 让用户自行选择是否采用这一特性.

**Comment by wish5115** [comment]
感谢反馈！

已改进这个功能。新版本下载地址：https://github.com/wish5115/obsidian-floating-settings/releases/tag/0.0.12

效果如图：

![comm2](https://github.com/wish5115/obsidian-floating-settings/assets/5248206/0505c0b2-583f-4215-9f5b-8928948b3d8f)
