### ISSUE TITLE
[FR] 更好地兼容插件`Setting Search`

### ISSUE THREAD

**Issue by XMB-7** [wish5115/obsidian-floating-settings#4]
`Setting Search`可以在ob选项页的左上角添加一个全局搜索框, 
<img src='https://github.com/wish5115/obsidian-floating-settings/assets/65625632/12d34ad3-6f52-4b96-af54-5930d16b20d0' width=500>

目前打开浮窗配置页面, 侧栏会自动地向下滚动到上一次浏览的插件条目, 导致需要手动滚动到顶才能重新在视野里看到全局搜索框并进行点击聚焦以及键入待搜索的内容. 但更好的方式其实是按一下shift+tab, 这样即可快速聚焦于最顶部的全局搜索框. 
但毕竟还是得手动按一下shift+tab, 因此希望能够自动实现. 最好的是, 如果用户同时开启`Setting Search`, 那么唤出配置页浮窗后, 先模拟于侧栏键入shift+tab, 以聚焦全局搜索框并全选其内容, 然后再向下滚动到上一次浏览的插件条目, 从而使用户既能定位到上次浏览的位置, 也能直接打字进行新一轮的搜索.

**Comment by wish5115** [comment]
你说的，这种不可能同时满足，因为二者是矛盾的，你要聚焦到顶部搜索，必然要滚动到顶部，不然搜索框看不到，但，如果上次打开的标签在底部，它就必然滚动到底部，不然也无法看到上次的标签，这样，既满足滚动顶部，又满足滚动底部是不可能的。除非让搜索框固定到顶部，不随滚动条滚动。如果需要搜索框固定到底部，通过css代码就可以实现了。

**Comment by XMB-7** [comment]
不需要啊, 先聚焦后滚动就可以了. 我只需要让搜索框聚焦, 并不需要让搜索框保持在视野里可见, 就算滚动到底部了, 只要搜索框还是聚焦的, 在底部也可以直接键入待搜索的内容.

**Comment by wish5115** [comment]
这样不行的，不信你输入试试，当你滚动到下面，一输入内容，马上就会滚动到上面。

为啥不要固定不动的效果，这样不挺好吗

**Comment by XMB-7** [comment]
我的意思是, 在我输入内容之前, 保持在上一次浏览的位置. 但当我都要搜索并即将打开新的配置页的时候, 当前浏览位置也就可以扔了, 我需要的恰好是自动回滚到上面啊.

具体比如, 我先看了z插件的配置页, 然后关了, 再打开, 此时自动滚到最底, 完了现在我想改搜a插件, 那不管搜索框固不固定, 它都不是自动聚焦的, 我怎么都得手动点一下或者按一下shift+tab吧. 现在我希望的是省略手动这一步, 亦即当我重新打开配置页时, 如果我不想搜新的插件, 它依然能自动保持停留在z上, 而一旦我想搜新的插件, 我直接打字就可以了, 因为在往下滚动前就已经聚焦到搜索框上了. 而当我开始打字时, 我自然也就不需要还停留在z上了, 此时合该滚到上面, 让我看到搜索框里我具体都键入了什么东西.

**Comment by wish5115** [comment]
嗯嗯，我了解你的需求了，但这有个前提，就是只能浏览，不能点击鼠标，一旦点击了鼠标，就失去输入框焦点了

**Comment by XMB-7** [comment]
感谢, 也怪我一开始就没直接具体说明. 
至于点击鼠标丢失搜索框聚焦的问题, 倒也可以通过先关闭再重新打开配置页来间接解决, 总之也不是什么大问题, 现在这样就已经很提高效率了.

**Comment by wish5115** [comment]
不客气，自动聚焦功能我只能尝试是否可行，因为这种操作，包括模拟点击等，通常受到浏览器限制（obsidian也是浏览器内核）不是用户操作，机器操作通常是禁止的。

**Comment by XMB-7** [comment]
我前一阵向note toolbar提过fr, 根据他的描述, 应该是可行的, 但具体情况就不知道了, 我对前端编程基本一窍不通.

> I don't mind adding this in the next release. It will use the same technique as I use in `Show Properties`, which is to find the metadata heading element, and issue a click on the heading. The new `Fold Properties` command will just issue the click only if it's not already collapsed.

**Comment by wish5115** [comment]
发送shift+tab是不可能的，你问问ai就知道了，click和focus一般是可以的，但不是所有控件所有场景都可以的。

**Comment by wish5115** [comment]
感谢建议！

已按照你所描述的方式改进了这个功能。

新版本下载：

https://github.com/wish5115/obsidian-floating-settings/releases/tag/0.0.13
